### ISSUE TITLE
nctl --version just shows `dev`

### ISSUE THREAD

**Issue by rnestler** [ninech/nctl#160] opened 2024-09-16 15:13 UTC
Since 1.7.4 `nctl --version` just shows `dev`:
```
% nctl --version
dev
```

I guess the reason is the change in https://github.com/ninech/nctl/commit/587c14bd92d38e61324c1cdca9ee5ebdb28605ac which changes the `version` from `var` to `const` and thus it's not overridable at link time anymore.

**Comment by thirdeyenick** [comment] 2024-09-18 09:30
This issue should be fixed in https://github.com/ninech/nctl/pull/162. So with the next released version this issue should not come up again.

**Comment by thirdeyenick** [comment] 2024-09-18 14:02
We just released `nctl` [v1.7.5](https://github.com/ninech/nctl/releases/tag/v1.7.5) which fixed this issue.

**Closed by thirdeyenick** 2024-09-18 14:02 UTC

**Comment by rnestler** [comment] 2024-09-18 15:53
It now shows `1.7.5-arch (commit: 11465dedde74d0764d2962f5716f31b5d68bbf82, date: 2024-09-16T15:06:16Z)` on my system which is the wrong commit, since I build from the source tar ball inside a git repository, so it picks up that git commit from there.

**Comment by thde** [comment] 2024-09-23 09:48
Yes, that should be fixed by https://github.com/ninech/nctl/pull/165

**Comment by thirdeyenick** [comment] 2024-09-24 11:10
Might this issue be caused by some specific Arch Linux build steps? I can't find the commit `11465dedde74d0764d2962f5716f31b5d68bbf82` in the repository. Go does VCS stamping by default when building. That is where the output information comes from.

**Comment by thirdeyenick** [comment] 2024-09-24 11:20
When executing the build steps contained in the repository `aur.archlinux.org/nctl.git` I end up with:

```
$> ./nctl --version
v1.7.5-arch (commit: , date: )
```

I am not sure where the commit from the initial description comes from, but we should maybe not show empty commits/dates in the version output.

**Comment by thirdeyenick** [comment] 2024-09-24 11:27
Sorry, I now read your [comment](https://github.com/ninech/nctl/issues/160#issuecomment-2358844823) and understand that you build in a git repository. I think you could just use `go build -buildvcs=false ...` when building for Arch Linux to disable VCS stamping. On the other hand, we need to remove the empty `commit` and `date` output.

**Comment by rnestler** [comment] 2024-09-25 09:06
> Sorry, I now read your https://github.com/ninech/nctl/issues/160#issuecomment-2358844823 and understand that you build in a git repository.

Yes, AUR packages are just git repositories, so it picks up the git commit from the AUR package locally.

> I think you could just use `go build -buildvcs=false ...` when building for Arch Linux to disable VCS stamping. On the other hand, we need to remove the empty commit and date output.

If I pass that flag I end up with the same output: `1.7.5-arch (commit: , date: )`

**Comment by thirdeyenick** [comment] 2024-09-25 12:06
We just merged a [commit](https://github.com/ninech/nctl/pull/167/commits/763d46a1ce1e0368b65e19eae1057ac5c294beab) which fixes this. So the next release of `nctl` should provide correct versioning information on Arch Linux (given that `-buildvcs=false` was used).

**Comment by rnestler** [comment] 2024-11-25 19:17
For future reference: It works correctly with the 1.8.0 release:
```
$ nctl --version
1.8.0-arch
```
